### ISSUE TITLE
サンプル数のアサーションがおかしい

### ISSUE THREAD

**Issue by habu1010** [rotildeof/FFT#1]
`assert( n_sample & (n_sample - 1) != 0);`
上記のコードはサンプル数を2のべき乗に制限するためのassertだと思いますが、正しく動作していません。
まず、C++(C言語)では比較演算子のほうがビット論理積演算子よりも優先順位が高いため、`n_sample & (n_sample - 1)`の部分を括弧でくくる必要があります。
また、n_sampleが2のべき乗であるという事を想定していると考えると、`n_sample & (n_sample - 1)`は0になるはずなので、`!= 0`ではなく`== 0`となるのが正解のはずです。

まとめると、
`assert((n_sample & (n_sample - 1)) == 0);`
が正しいです。

**Comment by rotildeof** [comment]
ご指摘ありがとうございます。
実は気づいていたのですが直すのを忘れていました(直しました)
多分これで動くようになったはずです。

**Comment by habu1010** [comment]
修正ありがとうございます。
修正コミットに余計な文字が混入してしまっていたので、その修正を今度はプルリクエストで送ってみました。
